### ISSUE TITLE
(建議)加上候選人年紀

### ISSUE THREAD

**Issue by up9cloud** [g0v/sunshine.cy#6]
您好，是否可以有一欄列出年齡呢。因為感覺政見都空頭支票跟出席也都是作秀，至少給年輕人多點機會。

**Comment by thewayiam** [comment]
2016 立委選舉，中選會以 api 提供選舉公報上資料（包含出生日期），已在立委投票指南實作，如無意外中選會也在 2018 提供 api 即無問題
