### ISSUE TITLE
本地化问题

### ISSUE THREAD

**Issue by AlifenCheng** [g0v/sunshine.cy#8]
你好，搭建完成后无法本地化是什么原因那？  修改过html让他加载了本地的css，可是网页的css依旧会加载失败。

**Comment by thewayiam** [comment]
Probably amazon s3 and google been blocked, you could edit css, js to where you are accessible.
css: https://github.com/g0v/sunshine.cy/blob/master/website/cy/templates/base.html#L20-L21
js: https://github.com/g0v/sunshine.cy/blob/master/website/cy/templates/base.html#L87-L88

**Comment by AlifenCheng** [comment]
I had already to edit base.html . And also I download the js ,css form source of website. but it is unuseful way.The website can loading but an error has appeared.

**Comment by thewayiam** [comment]
Could you provide the error message and screenshot of your browser network console?

**Comment by AlifenCheng** [comment]
The stylesheet http://127.0.0.1:8000/cy/website/cy/local/bootstrap.min.css was not loaded because its MIME type, “text/html”, is not “text/css”.

Sorry,I dont know how to upload the picture,This is the error message ,and the website dont have any style just word, I already tried to change the css type and the HTML head file（ <!DOCTYPE>）.Also didn‘’t solved.and sorry to brother you .

**Comment by thewayiam** [comment]
If you want to using local static files, please notice template tag and django setting, example as below:
template tag: https://github.com/g0v/councilor-voter-guide/blob/master/voter_guide/templates/base.html#L22
django setting: https://github.com/g0v/councilor-voter-guide/blob/master/voter_guide/voter_guide/settings.py#L70-L78

**Comment by AlifenCheng** [comment]
Thanks，I will try again.

**Comment by AlifenCheng** [comment]
Thanks，I will try again.

**Comment by AlifenCheng** [comment]
And I changed the link sentence, but the website service is wrong. Service Error 500.I edited the setting.py and Added Debug=false. Although Wrong.I am sorry that I dont konw very well about django. I studied your this program for 4 months. in order to learn  Docker and something about framework.
my static file in /cy/website/cy/static ,and I had no idea for setting.py .

**Comment by thewayiam** [comment]
Please set Debug=True and paste the error message in your console or browser here.
If you are tired of static files settings, I'll suggest upload static files to somewhere you can access and just using the link in html, that will be more easily.

**Comment by AlifenCheng** [comment]
GET http://127.0.0.1:8000/ [HTTP/1.0 500 INTERNAL SERVER ERROR 33ms]
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

I think I need declare the css and js file. I do but also false.

**Comment by thewayiam** [comment]
What's your browser, I google someone meet this problem with firefox, maybe try something below:

- `<meta http-equiv="content-type" content="text/html; charset=utf-8" />`(https://stackoverflow.com/questions/24604466/the-character-encoding-of-the-plain-text-document-was-not-declared-mootool-scr)

- use other browser or other version of firefox

**Comment by AlifenCheng** [comment]
sorry to apply you so late, Thanks for your help. and there are some py files also have some cite path I found.After a great deal of effort,I found some problems in css. There are also some loading in css files. so the static loading is really hard and I am not sure that it is a solution, but I will do it also.Pay tribute to knowledge.

**Comment by AlifenCheng** [comment]
Cheers! finally.I use the Apache to finish the static loading.

**Comment by AlifenCheng** [comment]
Hi there, I have one more question.Can I use your system to study?I will publish an article in my study log that deals.Only the analysis of reptile techniques and project frameworks.May I ask if I can get your authorization?

**Comment by thewayiam** [comment]
This project was CC0(https://github.com/g0v/sunshine.cy#cc0-10-universal), you are welcome to do that!

**Comment by AlifenCheng** [comment]
It's nice,Thanks.
